const mongoose = require('mongoose');

// An airline's own (internal) certificate for one candidate. Not generated by
// us — the airline / one of its departments uploads the PDF, which lives in
// Cloudflare R2 under `r2_key` (see services/r2.js).
const internalCertificateSchema = new mongoose.Schema({
  participant:   { type: mongoose.Schema.Types.ObjectId, ref: 'Participant', required: true, index: true },
  // Top-level airline the certificate belongs to (departments roll up to it).
  owner_airline: { type: mongoose.Schema.Types.ObjectId, ref: 'Airline', default: null, index: true },
  // Account that uploaded it — the airline itself, a department, or an admin.
  uploaded_by:      { type: mongoose.Schema.Types.ObjectId, default: null },
  uploaded_by_role: { type: String, enum: ['airline', 'admin'], default: 'airline' },
  uploaded_by_name: { type: String, default: '' },

  title:         { type: String, default: '', trim: true },
  issued_on:     { type: Date, default: null },
  expires_on:    { type: Date, default: null },
  // Explicitly valid forever (vs. expires_on simply left blank).
  no_expiry:     { type: Boolean, default: false },

  r2_key:        { type: String, required: true },
  original_name: { type: String, default: '' },
  size:          { type: Number, default: 0 },   // bytes stored in R2 (after compression)
  original_size: { type: Number, default: 0 },   // bytes as uploaded
}, { timestamps: true });

internalCertificateSchema.methods.toJSON = function () {
  const obj = this.toObject();
  obj._id = String(obj._id);
  obj.id = obj._id;
  delete obj.r2_key;
  return obj;
};

module.exports = mongoose.model('InternalCertificate', internalCertificateSchema);
